pybites/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^pyplanet/', include('pyplanet.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'template_name': 'logged_out.html'}, name='logout'),
]

pyplanet/urls.py
from django.conf.urls import url

from . import views

app_name = 'pyplanet'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<article_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<article_id>[0-9]+)/skip/$', views.skip, name='skip'),
    url(r'^(?P<article_id>[0-9]+)/share/$', views.share, name='share'),
]

pyplanet/models.py
from django.contrib.auth.models import User
from django.db import models

class Article(models.Model):
    OPEN = 0
    SKIPPED = 1
    SHARED = 2
    STATUSES = (
        (OPEN, 'Open'),
        (SKIPPED, 'Skipped'),
        (SHARED, 'Shared'),
    )

    title = models.CharField(max_length=300, unique=True)
    url = models.CharField(max_length=200, unique=True)
    summary = models.TextField(blank=True, null=True)
    published = models.DateTimeField(null=True)
    status = models.IntegerField(
        choices=STATUSES,
        default=OPEN,
    )

    edited = models.DateTimeField(auto_now=True)
    # TODO: populate when we have login
    edited_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.title

pybites/views.py
from django.http import HttpResponse
from django.template import loader

def index(request):
    template = loader.get_template('index.html')
    context = {
        'title': 'Welcome',
    }
    return HttpResponse(template.render(context, request))

pyplanet/views.py
from urllib.parse import urlencode, quote_plus

from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.shortcuts import get_object_or_404, render

from .models import Article

OPEN = 0
SKIPPED = 1
SHARED = 2
MAX_ENTRIES = 100
PYBITES = 'pybit.es'
TWITTER_INTENT = 'https://twitter.com/intent/tweet?'


def index(request):
    articles = Article.objects.order_by('-published')[:MAX_ENTRIES]
    template = loader.get_template('pyplanet/index.html')
    context = {
        'title': 'Articles',
        'articles': articles,
    }
    return HttpResponse(template.render(context, request))


def detail(request, article_id):
    article = get_object_or_404(Article, pk=article_id)

    article_text = article.title
    if PYBITES in article.url:
        article_text = 'New PyBites Article: ' + article_text

    payload = {'text': article_text, 'url': article.url}
    tweet_url_su = TWITTER_INTENT + urlencode(payload, quote_via=quote_plus)
    payload['via'] = 'pybites'
    tweet_url_guest = TWITTER_INTENT + urlencode(payload, quote_via=quote_plus)

    return render(request, 'pyplanet/detail.html', 
                  {'title': 'Article Detail',
                   'article': article,
                   'tweet_url_su': tweet_url_su,
                   'tweet_url_guest': tweet_url_guest,
                   })


def _update(request, article_id, status):
    article = get_object_or_404(Article, pk=article_id)
    article.status = status
    # TODO - edited_by
    article.save()
    return HttpResponseRedirect('/pyplanet')


def skip(request, article_id):
    return _update(request, article_id, SKIPPED)


def share(request, article_id):
    return _update(request, article_id, SHARED)

pybites/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
	<title>PyBites 100 Days of Django</title>
	{% load static %}
	<link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css">
	<link rel="stylesheet" type="text/css" href="{% static 'pyplanet/style.css' %}" />
	<script type="text/javascript" async src="https://platform.twitter.com/widgets.js"></script>
  </head>
  <body>
  <header>
    <h1>{% block title %}{% endblock %}</h1>

    <div id="login">
	  {% if user.is_authenticated %}
        Welcome back, {{ user.username }}!  <a href="{% url 'logout' %}">Logout</a>

		{% if user.is_superuser %}
	      &nbsp;|&nbsp;<a href="{% url 'admin:index' %}">Admin</a>
        {% endif %}

	  {% elif 'login' not in request.build_absolute_uri %}
        <a href="{% url 'login' %}">Login</a>
      {% endif %}

	  &nbsp;|&nbsp;<a href="{% url 'index' %}">Home</a>
    </div>

  </header>

  <main>
    {% block content %}
    {% endblock %}
  </main>
  <br>
  <hr>
  <footer>
    Created by <a href="https://pybit.es" target="_blank">PyBites</a> as <a href="https://github.com/pybites/pyplanet-django" target="_blank">first app</a> for our <a href="https://pybit.es/special-100days-of-code.html" target="_blank">100 Days of Django</a>
  </footer>
</body>
</html>

pybites/templates/index.html
{% extends 'base.html' %}

{% block title %}PyBites 100 Days of Django{% endblock %}

{% block content %}
  <p>Here we will deploy the apps we build. </p>
  <ul>
	<li><a href='pyplanet'>PyPlanet Article Sharer App</a></li>
  </ul>
{% endblock %}

pybites/templates/logged_out.html
{% extends 'base.html' %}

{% block title %}See you!{% endblock %}

{% block content %}
  <p>You have been successfully logged out.</p>
{% endblock %}

pybites/templates/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
  <form class="pure-form" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="pure-button pure-button-primary">Login</button>
  </form>
{% endblock %}

pyplanet/templates/pyplanet/detail.html
{% extends 'base.html' %}

{% block content %}

	<h2><a href='{{ article.url }}'>{{ article.title }}</a></h2>

    <div class="pure-button-group" role="group" aria-label="...">
	    {% if user.is_superuser %}

			{% if article.status == 0 %}
				<a class="pure-button pure-button-primary" href='{{ tweet_url_su }}' target="_blank">Tweet this</a>
				<a class="pure-button button-success" href='{% url 'pyplanet:share' article.id %}'>Mark Shared</a>
				<a class="pure-button button-warning" href='{% url 'pyplanet:skip' article.id %}'>Mark Skipped</a>
			{% elif article.status == 1 %}
				<button class="pure-button button-warning pure-button-disabled">Already skipped</button>
			{% elif article.status == 2 %}
				<button class="pure-button button-success pure-button-disabled">Already shared</button>
			{% endif %}

	    {% elif user.is_authenticated %}

			<a class="pure-button pure-button-primary" href='{{ tweet_url_guest }}' target="_blank">Tweet this</a>

        {% endif %}

        <a class='pure-button pure-button-active' href="{% url 'pyplanet:index' %}">Go back</a>
    </div>

    <br>
    <hr>

	<h3>Article: </h3>

	<p>(published: {{ article.published }})</p>

	{{ article.summary|safe }}

{% endblock %}

pyplanet/templates/pyplanet/index.html
{% extends 'base.html' %}

{% block content %}

	{% if articles %}
		<table class='pure-table'>
			<thead>
				<th>Title</th>
			</thead>
			<tbody>
			{% for article in articles %}
			  <tr>
	             {% if article.status == 1 %}
                   <td class='skipped'>
	             {% elif article.status == 2 %}
                   <td class='shared'>
  	             {% else %}
                   <td>
                 {% endif %}
                   <a href="{% url 'pyplanet:detail' article.id %}">{{ article.title }}</a>
                 </td>
			  </tr>
			{% endfor %}
			</tbody>
		</table>
	{% else %}
		<p>No articles available.</p>
	{% endif %}

{% endblock %}